# version: '3.8'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     environment:
#       - DB_HOST=${DB_HOST}
#       - DB_PORT=${DB_PORT}
#       - DB_USER=${DB_USER}
#       - DB_PASSWORD=${DB_PASSWORD}
#       - DB_DATABASE=${DB_DATABASE}
#       - DB_SSL_MODE=${DB_SSL_MODE}
#       - DB_URL=${DB_URL}
#       - JWT_SECRET=${JWT_SECRET}
#       - RABBITMQ_URL=${RABBITMQ_URL}
#     depends_on:
#       - db
#       - rabbitmq
#     networks:
#       - backend-network

#   db:
#     image: postgres:15
#     environment:
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#       POSTGRES_DB: ${DB_DATABASE}
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"
#     networks:
#       - backend-network

#   rabbitmq:
#     image: rabbitmq:management
#     environment:
#       RABBITMQ_DEFAULT_USER: "user"
#       RABBITMQ_DEFAULT_PASS: "password"
#     ports:
#       - "5672:5672"
#       - "15672:15672"
#     networks:
#       - backend-network

# volumes:
#   postgres_data:

# networks:
#   backend-network:






services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command:  npm start
    env_file:
      - .env
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_SSL_MODE=${DB_SSL_MODE}
      - DB_DATABASE_URL=${DB_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
     
    depends_on:
      - db2
    
    # networks:
    #   - backend-network
    volumes:
      - .:/usr/src/app
      - /usr/srcapp/node_modules
  
  rabbitmq:
    image: rabbitmq:3-management
    # networks:
    #   - auth-network
    ports:
      - "5672:5672"
     
    # networks:
    #   - backend-network



  db2:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5000:5432"
    # networks:
    #   - backend-network

volumes:
  postgres_data:
    driver: local
  

# networks:
#   backend-network: